## DSTEP20 // Application Programming Interface (API)

<small> January 17, 2020 </small>

In many contexts, API is a "catch all" term for syntax.  For example, [this is the pandas api documentation](https://pandas.pydata.org/pandas-docs/stable/reference/index.html).

In the context of web-based interaction, API refers specifically to the syntax used to interact with web resources, including **data sets**.

By way of example, let's look at the Socrata Open Data API.

### SODA: the Socrata Open Data API

<img src="https://dev.socrata.com/img/snuffleupacan.png" width=150px>

[Socrata](https://www.tylertech.com/products/socrata) is the currently most popular backend software used by governments to serve up data <small> (though recall that Minneapolis was using an Esri backend) </small>.  It provides functionality to

- send requests for data access
- download capabilities

First things first, let's install sodapy, a useful tool for dealing with Socrata backends:

In [0]:
!pip install sodapy

Collecting sodapy
  Downloading https://files.pythonhosted.org/packages/64/06/6144b36a4b4470bef1fb17d7b98b82a202b5e918f7e0a2c123004f73ca07/sodapy-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.6/dist-packages (from sodapy) (2.21.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (1.24.3)
Installing collected packages: sodapy
Successfully installed sodapy-2.0.0

There are three fundamental variables you need when accessing data via web-based APIs:

- the domain (or endpoint)
- dataset identifier
- query parameters

Let's use [NYC's 311](https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9) complaint call in line data as an example.  First, we need to locate the **domain** and **dataset identifier**.  Our **query parameters** in this case will be a simple limit on the number of records that we get.

In [0]:
# -- import useful functionality
import numpy as np
import pandas as pd
import sodapy

In [0]:
# -- set the domain endpoint
dom  = "data.cityofnewyork.us"
dsid = "erm2-nwe9"
lim  = 100000

# -- open the "client"
#    nb, for the moment, this is for public data with no access token
client = sodapy.Socrata(dom, None, timeout=120)

# -- pull the data from the domain into a list of dictionaries
result = client.get(dsid, limit=lim)

# -- convert to dataframe
data = pd.DataFrame.from_records(result)

In [0]:
# -- as always, print the data, column names, number of NaN values, etc.
print(data)
print("")
print(data.columns)
print("")
print(data.isna().sum(axis=0))

      unique_key             created_date  ... vehicle_type bridge_highway_name
0       45397049  2020-01-16T02:01:19.000  ...          NaN                 NaN
1       45393008  2020-01-16T02:00:57.000  ...          NaN                 NaN
2       45394106  2020-01-16T02:00:46.000  ...          NaN                 NaN
3       45397614  2020-01-16T02:00:14.000  ...          NaN                 NaN
4       45394020  2020-01-16T01:59:56.000  ...          NaN                 NaN
...          ...                      ...  ...          ...                 ...
99995   45264441  2019-12-28T09:16:39.000  ...          NaN                 NaN
99996   45261020  2019-12-28T09:16:35.000  ...          NaN                 NaN
99997   45263321  2019-12-28T09:16:30.000  ...          NaN                 NaN
99998   45260580  2019-12-28T09:16:12.000  ...          NaN                 NaN
99999   45259903  2019-12-28T09:16:10.000  ...          NaN                 NaN

[100000 rows x 46 columns]

Index(['unique_key', 'created_date', 'agency', 'agency_name', 'complaint_type',
       'descriptor', 'location_type', 'incident_zip', 'incident_address',
       'street_name', 'cross_street_1', 'cross_street_2',
       'intersection_street_1', 'intersection_street_2', 'city', 'landmark',
       'status', 'community_board', 'bbl', 'borough',
       'x_coordinate_state_plane', 'y_coordinate_state_plane',
       'open_data_channel_type', 'park_facility_name', 'park_borough',
       'latitude', 'longitude', 'location', ':@computed_region_efsh_h5xi',
       ':@computed_region_f5dn_yrer', ':@computed_region_yeji_bk3q',
       ':@computed_region_92fq_4b7q', ':@computed_region_sbqj_enih',
       'taxi_pick_up_location', 'closed_date', 'resolution_description',
       'resolution_action_updated_date', 'address_type', 'facility_type',
       'due_date', 'bridge_highway_direction', 'road_ramp',
       'bridge_highway_segment', 'taxi_company_borough', 'vehicle_type',
       'bridge_highway_name'],
      dtype='object')

unique_key                            0
created_date                          0
agency                                0
agency_name                           0
complaint_type                        0
descriptor                          892
location_type                     29166
incident_zip                       3604
incident_address                   6876
street_name                        6878
cross_street_1                    32441
cross_street_2                    32514
intersection_street_1             40012
intersection_street_2             40012
city                               8054
landmark                          50850
status                                0
community_board                       0
bbl                               15115
borough                               0
x_coordinate_state_plane           4225
y_coordinate_state_plane           4225
open_data_channel_type                0
park_facility_name                    0
park_borough                          0
latitude                           4225
longitude                          4225
location                           4225
:@computed_region_efsh_h5xi        4402
:@computed_region_f5dn_yrer        4243
:@computed_region_yeji_bk3q        4243
:@computed_region_92fq_4b7q        4243
:@computed_region_sbqj_enih        4243
taxi_pick_up_location             98212
closed_date                       16626
resolution_description             8502
resolution_action_updated_date     6980
address_type                      53310
facility_type                     86688
due_date                          99463
bridge_highway_direction          99816
road_ramp                         99816
bridge_highway_segment            99816
taxi_company_borough              99898
vehicle_type                      99964
bridge_highway_name               99990
dtype: int64

As with direct URL querying, we can make queries (and subselect columns):

In [0]:
# -- pull the data from the domain into a list of dictionaries
result_sel = client.get(dsid, limit=lim, select="borough,bbl,agency,unique_key", 
                        where="agency='NYPD'")

# -- convert to dataframe
sub = pd.DataFrame.from_records(result_sel)

Let's check if we're getting the same records each time:

In [0]:
# -- first print the first 10 rows of the sub selection
print(sub[:10])

# -- now we'll recreate the selection and print the first 10
ind = data["agency"] == "NYPD"

print("")
print(data[["agency", "bbl", "borough", "unique_key"]][ind][:10])

     borough agency unique_key         bbl
0  MANHATTAN   NYPD   45399033         NaN
1   BROOKLYN   NYPD   45398371  3018630026
2  MANHATTAN   NYPD   45398124  1010200038
3  MANHATTAN   NYPD   45396335  1016730006
4     QUEENS   NYPD   45397059  4027040093
5   BROOKLYN   NYPD   45397752  3065860057
6   BROOKLYN   NYPD   45399099         NaN
7     QUEENS   NYPD   45399078  4136430029
8   BROOKLYN   NYPD   45399395  3009497504
9   BROOKLYN   NYPD   45396629  3047800026

  agency         bbl    borough unique_key
0   NYPD  1020080006  MANHATTAN   45397049
1   NYPD  2032090021      BRONX   45393008
2   NYPD  2029020036      BRONX   45394106
3   NYPD  2024360008      BRONX   45397614
4   NYPD  1020360038  MANHATTAN   45394020
5   NYPD  2031150005      BRONX   45398062
6   NYPD  2055760092      BRONX   45398569
7   NYPD  2024360008      BRONX   45396636
8   NYPD  2029020036      BRONX   45399116
9   NYPD  3065030083   BROOKLYN   45396971

**Note that we are not getting exactly the same records!**

Let's try one more request to demonstrate working with timestamps (note: sodapy accepts [SoQL](https://dev.socrata.com/docs/queries/)-like queries):

In [0]:
# -- put together a more complex query
aquery = "agency='NYPD'"
dquery = "created_date between '2015-03-26T00:00:00' and '2015-03-27T00:00:00.000'"
fullq  = aquery + " and " + dquery

# -- pull the data from the domain into a list of dictionaries
result3 = client.get(dsid, limit=lim, select="borough,bbl,agency,unique_key,created_date", 
                     where=fullq)

# -- convert to dataframe
data3 = pd.DataFrame.from_records(result3)

In [0]:
print(data3)

        borough agency unique_key             created_date         bbl
0        QUEENS   NYPD   30263290  2015-03-26T00:00:33.000         NaN
1     MANHATTAN   NYPD   30259913  2015-03-26T00:00:38.000  1016800030
2         BRONX   NYPD   30261009  2015-03-26T00:03:36.000  2023240001
3         BRONX   NYPD   30257805  2015-03-26T00:05:21.000  2023240001
4         BRONX   NYPD   30262656  2015-03-26T00:06:17.000         NaN
...         ...    ...        ...                      ...         ...
1176   BROOKLYN   NYPD   30263782  2015-03-26T23:54:01.000  3068260048
1177     QUEENS   NYPD   30267577  2015-03-26T23:55:42.000  4083510048
1178  MANHATTAN   NYPD   30265772  2015-03-26T23:55:47.000  1020270001
1179      BRONX   NYPD   30268419  2015-03-26T23:56:24.000         NaN
1180      BRONX   NYPD   30263877  2015-03-26T23:58:36.000         NaN

[1181 rows x 5 columns]

**Note that, because we restricted to only 1 day, our limit is > the total number for that day so we are getting them all in this case.**